# Generated by Django 4.2.16 on 2025-05-22 01:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True)),
                ('fin_co_no', models.CharField(max_length=20)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('join_way', models.TextField()),
                ('join_deny', models.CharField(max_length=10)),
                ('join_member', models.TextField()),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=20, null=True)),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('interest_detail', models.JSONField(default=dict)),
                ('lowest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('highest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dcls_month', models.CharField(max_length=10)),
                ('dcls_strt_day', models.DateField()),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
                ('fin_co_subm_day', models.DateTimeField()),
                ('record_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=20)),
                ('record_date', models.DateField()),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('daily_change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('high_52w', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('low_52w', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('aum', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'record_date', 'data_type')},
            },
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('average_buy_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='UserDailyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('score', models.DecimalField(decimal_places=4, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'record_date')},
            },
        ),
    ]
