# Generated by Django 4.2.16 on 2025-05-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userportfolio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDailyRanking',
        ),
        migrations.DeleteModel(
            name='UserPortfolio',
        ),
    ]
