# Generated by Django 4.2.16 on 2025-05-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_userportfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtfDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('price_krw', models.CharField(blank=True, max_length=30, null=True)),
                ('price_usd', models.CharField(blank=True, max_length=30, null=True)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
                ('marketcap', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.CharField(blank=True, max_length=50, null=True)),
                ('list_date', models.CharField(blank=True, max_length=30, null=True)),
                ('nav', models.CharField(blank=True, max_length=30, null=True)),
                ('fee', models.CharField(blank=True, max_length=30, null=True)),
                ('gap', models.CharField(blank=True, max_length=30, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('holdings', models.JSONField(blank=True, default=list)),
                ('dividends', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
