# Generated by Django 4.2.16 on 2025-05-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treestatus',
            name='good_spending_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treestatus',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='treestatus',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
