# Generated by Django 4.2.16 on 2025-05-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='account_num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spending',
            name='card_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='spending',
            name='currency_code',
            field=models.CharField(default='KRW', max_length=5),
        ),
        migrations.AddField(
            model_name='spending',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spending',
            name='source',
            field=models.CharField(choices=[('카드', '카드'), ('계좌', '계좌')], default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spending',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='spending',
            name='trans_memo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spending',
            name='trans_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
